config/routes.rb
Rails.application.routes.draw do
  resources :songs do
    collection { post :import}
  end
  get 'subscriptions', to: 'subscription#index'
  devise_for :users, :paths => 'users'
  resources :users do
    resources :payments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :broadcasters, except: [:show]
  resources :genres
  resources :datalists, only: [:new, :create]
  get 'payments/pending', to: 'payments#pendingpayments'
  # patch 'payments/pending', to: 'payments#update'
  get 'broadcasters/manage', to: 'broadcasters#manage'
  get 'administration/users', to: 'admins#manageusers'
  get 'administration', to: 'admins#index'
  get 'billboard', to: 'billboards#index'
  get 'billboard/top_100', to: 'billboards#top_100'
  get 'billboard/top_latino', to: 'billboards#top_latino'
  get 'billboard/top_tradicional', to: 'billboards#top_tradicional'
  get 'billboard/top_balada', to: 'billboards#top_balada'
  get 'billboard/top_salsa', to: 'billboards#top_salsa'
  get 'billboard/top_pop', to: 'billboards#top_pop'
  get 'billboard/top_rock', to: 'billboards#top_rock'
  get 'billboard/top_emisoras', to: 'billboards#top_emisoras'
  get 'contact', to: 'contact#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/broadcaster.rb
class Broadcaster < ApplicationRecord
  validates :name, :email, :phone, :ref, :location, :contact_name, presence: true
  validates :name, uniqueness: true
end

app/models/datalist.rb
class Datalist < ApplicationRecord
  # validates :list_date, :list, presence: true
  has_one_attached :list
  validate :correct_file_type

  private

  def correct_file_type
    if list.attached? && !list.content_type.in?(%w(text/plain))
      errors.add(:list, 'Seleccionar solo archivos con extensión .txt /')
    end
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
  enum paid_out: [:pendiente, :procesado]
  validates :invoice, :paid_out, presence: true
  validate :correct_file_type
  has_one_attached :invoice

  # after_update :set_user_active
  accepts_nested_attributes_for :user, update_only: true

  private

    def correct_file_type
      if invoice.attached? && !invoice.content_type.in?(%w(image/jpg image/jpeg image/png application/pdf))
        errors.add(:invoice, 'Seleccionar solo archivos con extensión .jpg / .jpeg / .png / .pdf')
      end
    end

    # def set_user_active
    #   @user = User.find(params[:id])
    #   @user.status = 'activo'
    #   @user.save
    # end
end

app/models/song.rb
class Song < ApplicationRecord
  require 'csv'
  # validate :correct_file_type

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Song.create! row.to_hash
    end
  end

  private

  # def correct_file_type
  #   if file.attached? && !file.content_type.in?(%w(text/csv))
  #     errors.add(:file, 'Seleccionar solo archivos con extensión .csv /')
  #   end
  # end

end

app/models/user.rb
class User < ApplicationRecord
  enum role: [:regular, :admin]
  enum status: [:inactivo, :activo]
  has_many :payments

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  after_initialize :set_default_role, :set_default_status, :if => :new_record?

  # accepts_nested_attributes_for :payments, reject_if: :all_blank

  def set_default_role
    self.role ||= :regular
  end

  def set_default_status
    self.status ||= :inactivo
  end

end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin
  layout :resolve_layout
  def index
  end

  def manageusers
    @users = User.where(role: 'regular')

  end

  private

  def authenticate_admin
    if current_user.role != 'admin'
      redirect_back fallback_location: root_path, alert: "No posee los permisos necesarios"
    end
  end

  def resolve_layout
    case action_name
    when "manageusers"
      "admin"
    end
  end

end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index

  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre, only: [:show, :edit, :update, :destroy]
  layout :resolve_layout
  def index
    @genres = Genre.all
  end

  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to genres_path, notice: '¡ Género Musical Agregado Correctamente !'
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @genre.update(genre_params)
      redirect_to genres_path, notice: '¡ Género Musical Actualizado Correctamente !'
    else
      redirect_to genres_path, alert: '¡ No se pudo Actualizar el registro seleccionado !'
    end
  end

  def destroy
    if @genre.destroy
      redirect_to genres_path, notice: '¡ Género Musical Eliminado Correctamente !'
    else
      redirect_to genres_path, alert: '¡ No se pudo Elimina el registro seleccionado !'
    end
  end

  private

  def set_genre
    @genre = Genre.find(params[:id])
  end

  def genre_params
    params.require(:genre).permit(:name)
  end

  def resolve_layout
    case action_name
    when "index", "new"
      "admin"
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'animation'
  def index
    
  end
  
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin
  layout :resolve_layout
  def new
  end

  def create
    Song.import(params[:file])
    redirect_to new_song_path, notice: "Lista de canciones agregadas correctamente!"
  end

  private
  def authenticate_admin
    if current_user.role != 'admin'
      redirect_back fallback_location: root_path, alert: "No posee los permisos necesarios"
    end
  end


  def resolve_layout
    case action_name
    when "new"
      "admin"
    end
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/billboards_helper.rb
module BillboardsHelper
end

app/helpers/broadcasters_helper.rb
module BroadcastersHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/datalists_helper.rb
module DatalistsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/subscription_helper.rb
module SubscriptionHelper
end

app/views/genres/edit.html.haml
= render 'shared/genre_form'

app/views/genres/index.html.haml
.row.mb-3.headercontent
  .col-1
    = link_to administration_path, method: 'get' do
      = image_tag 'izquierda.svg'
.row.headercontent
  .col-3
    = image_tag ('pop.svg'), heigth: '200px', width:'200px', class: ''
  .col-9
    .row.contenttitle.d-flex.justify-content-center.mb-2
      Gestión de Género Musical
    .row.contenttext.text-muted
      En esta sección podras agregar, editar y/o eliminar géneros musicales.
    - if @genres.present?
      .row.signindiv.mt-3
        .col.d-flex.justify-content-end
          = link_to new_genre_path, method: 'get', class: 'btn', id: 'signinbutton' do
            Agregar Genero musical
#lineaseparadora.mt-2
  %hr
- if @genres.present?
  .row.mt-3.justify-content-center.bodycontent.mb-5
    .col-6
      %table{class: 'table table-hover table-bordered', id: 'genreborder'}
        %thead.text-center
          %tr
            %th{colspan: '2'} Géneros Musicales Registrados
        %tbody.text-center
          - @genres.each do |genre|
            %tr
              %td= genre.name
              %td.dropdown.dropright
                %button#dropdownMenuButton.btn{type: 'button', 'data-toggle':"dropdown", 'aria-haspopup': "true", 'aria-expanded': "false"}
                  = image_tag 'menu.svg'
                .dropdown-menu#dropdownmenu{"aria-labelledby" => "dropdownMenuButton"}
                  .dropdown-item#dropdownmenuitem
                    = link_to edit_genre_path(genre.id), class: '', id: 'optionbutton' do
                      .row
                        .col-3
                          = image_tag 'pencil.svg'
                        .col-9
                          Editar
                  .dropdown-item#dropdownmenuitem
                    = link_to genre_path(genre.id), method: 'delete', data: {confirm: '¿Esta seguro de eliminar este género?'}, class: '', id: 'optionbutton' do
                      .row
                        .col-3
                          = image_tag 'bin.svg'
                        .col-9
                          Eliminar
- else
  .row.bodycontent
    .col-12
      .row.justify-content-center.mt-5
        = link_to new_genre_path, method: 'get' do
          = image_tag 'añadirpago.svg'
      .row.justify-content-center
        = link_to new_genre_path, method: 'get', id: 'forgot-password' do
          Presiona para agregar un nuevo género musical

app/views/genres/new.html.haml
= render 'shared/genre_form'

app/views/songs/create.html.haml
%h1 Songs#create
%p Find me in app/views/songs/create.html.haml

app/views/songs/import.html.haml
%h1 Songs#import
%p Find me in app/views/songs/import.html.haml

app/views/songs/index.html.haml
= flash[:notice]
%div
  = form_with(url: import_songs_path, local: true, multipart:true, id: "songlistform") do |form|
    .field
      .row.form-group
        .col-sm-12.col-form-label
          .font-roboto-form= form.label :file, 'Lista de canciones:'
          = form.file_field :file, class: 'dropify'
      = form.hidden_field :fecha, value: Time.now.strftime('%Y-%m-%d')
    .actions
      .row.mt-4
        .col.text-center
          = form.submit("CARGAR",:class => "btn btn-lg", :id => "form-user-button")

app/views/songs/new.html.haml
.row.headercontent
  .col-1
    = link_to administration_path, method: 'get' do
      = image_tag 'izquierda.svg'
.row.headercontent
  .col-3
    = image_tag 'radio.svg'
  .col-9
    .row.contenttitle.d-flex.justify-content-center.mb-2
      Nueva lista de canciones
    .row.contenttext.text-muted
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
#lineaseparadora.mt-2
  %hr
.row.bodycontent
  .col-12
    .row.justify-content-center.mb-3.mt-3
      .col-10
        .row
          Estimado administrador, para añadir una lista de canciones sonadas en el dia en una de las emisoras analizadas, debes adjuntar un archivo en formato .txt con el siguiente formato:
    .row.justify-content-center
      = image_tag ('añadirpago.svg'), data: { target: '#modalpagos', toggle: 'modal', id: 'imagepointer' }
    .row.justify-content-center.mt-3
      %button.btn#form-user-button{ data: { target: '#modalpagos', toggle: 'modal' } }
        Quiero enviar una nueva lista!
    #modalpagos.modal.fade.mt-5
      .modal-dialog
        .modal-content#contenidodelmodal
          .modal-header.text-center.shadow.p-3.rounded.mb-2
            %h4.modal-title.white-text.w-100.font-weight-bold.py-2 Nueva Lista
            %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
              %span.white-text{"aria-hidden" => "true"} ×
          .modal-body
            = form_with(url: songs_path, local: true, multipart:true, id: "songlistform") do |form|
              .field
                .row.form-group
                  .col-sm-12.col-form-label
                    .font-roboto-form= form.label :file, 'Lista de canciones:'
                    = form.file_field :file, class: 'dropify'
                = form.hidden_field :fecha, value: Time.now.strftime('%Y-%m-%d')
              .actions
                .row.mt-4
                  .col.text-center
                    = form.submit("CARGAR",:class => "btn btn-lg", :id => "form-user-button")