config/routes.rb
Rails.application.routes.draw do
  resources :songs do
    collection { post :import}
  end
  get 'subscriptions', to: 'subscription#index'
  devise_for :users, :paths => 'users'
  resources :users do
    resources :payments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :broadcasters, except: [:show]
  resources :genres
  resources :datalists, only: [:new, :create]
  get 'payments/pending', to: 'payments#pendingpayments'
  # patch 'payments/pending', to: 'payments#update'
  get 'broadcasters/manage', to: 'broadcasters#manage'
  get 'administration/users', to: 'admins#manageusers'
  get 'administration', to: 'admins#index'
  get 'billboard', to: 'billboards#index'
  get 'billboard/top_100', to: 'billboards#top_100'
  get 'billboard/top_latino', to: 'billboards#top_latino'
  get 'billboard/top_tradicional', to: 'billboards#top_tradicional'
  get 'billboard/top_balada', to: 'billboards#top_balada'
  get 'billboard/top_salsa', to: 'billboards#top_salsa'
  get 'billboard/top_pop', to: 'billboards#top_pop'
  get 'billboard/top_rock', to: 'billboards#top_rock'
  get 'billboard/top_emisoras', to: 'billboards#top_emisoras'
  get 'contact', to: 'contact#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/broadcaster.rb
class Broadcaster < ApplicationRecord
  validates :name, :email, :phone, :ref, :location, :contact_name, presence: true
  validates :name, uniqueness: true
end

app/models/datalist.rb
class Datalist < ApplicationRecord
  # validates :list_date, :list, presence: true
  has_one_attached :list
  validate :correct_file_type

  private

  def correct_file_type
    if list.attached? && !list.content_type.in?(%w(text/plain))
      errors.add(:list, 'Seleccionar solo archivos con extensión .txt /')
    end
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
  enum paid_out: [:pendiente, :procesado]
  validates :invoice, :paid_out, presence: true
  validate :correct_file_type
  has_one_attached :invoice

  # after_update :set_user_active
  accepts_nested_attributes_for :user, update_only: true

  private

    def correct_file_type
      if invoice.attached? && !invoice.content_type.in?(%w(image/jpg image/jpeg image/png application/pdf))
        errors.add(:invoice, 'Seleccionar solo archivos con extensión .jpg / .jpeg / .png / .pdf')
      end
    end

    # def set_user_active
    #   @user = User.find(params[:id])
    #   @user.status = 'activo'
    #   @user.save
    # end
end

app/models/song.rb
class Song < ApplicationRecord
  require 'csv'
  # validate :correct_file_type

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Song.create! row.to_hash
    end
  end

  private

  # def correct_file_type
  #   if file.attached? && !file.content_type.in?(%w(text/csv))
  #     errors.add(:file, 'Seleccionar solo archivos con extensión .csv /')
  #   end
  # end

end

app/models/user.rb
class User < ApplicationRecord
  enum role: [:regular, :admin]
  enum status: [:inactivo, :activo]
  has_many :payments

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  after_initialize :set_default_role, :set_default_status, :if => :new_record?

  # accepts_nested_attributes_for :payments, reject_if: :all_blank

  def set_default_role
    self.role ||= :regular
  end

  def set_default_status
    self.status ||= :inactivo
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'animation'
  def index
    
  end
  
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin
  layout :resolve_layout
  def new
  end

  def create
    Song.import(params[:file])
    redirect_to new_song_path, notice: "Lista de canciones agregadas correctamente!"
  end

  private
  def authenticate_admin
    if current_user.role != 'admin'
      redirect_back fallback_location: root_path, alert: "No posee los permisos necesarios"
    end
  end


  def resolve_layout
    case action_name
    when "new"
      "admin"
    end
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/billboards_helper.rb
module BillboardsHelper
end

app/helpers/broadcasters_helper.rb
module BroadcastersHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/datalists_helper.rb
module DatalistsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/subscription_helper.rb
module SubscriptionHelper
end

app/views/admins/index.html.haml
.row.headercontent
  .col-3.mt-2
    = image_tag 'admin.svg'
  .col-9
    .row.contenttitle.d-flex.justify-content-center.mb-2
      Gestión del sistema
    .row.contenttext.text-muted
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
#lineaseparadora.mt-2
  %hr
.row.mt-5.bodycontent
  .col-3
    = link_to new_song_path, method: 'get', id: 'linksections' do
      .card#card-admin.d-flex.d-flex
        .card-body.align-items-center.d-flex.justify-content-center.align-items-center.d-flex.justify-content-center
          .row
            .col
              %h5{class: 'card-title text-center font-italic '} Agregar Lista de Canciones
  .col-3
    = link_to broadcasters_manage_path, method: 'get', id: 'linksections' do
      .card#card-admin.d-flex
        .card-body.align-items-center.d-flex.justify-content-center
          .row
            .col
              %h5{class: 'card-title text-center font-italic'} Gestionar Emisoras
  .col-3
    = link_to billboard_top_100_path, method: 'get', id: 'linksections' do
      .card#card-admin.d-flex
        .card-body.align-items-center.d-flex.justify-content-center
          .row
            .col
              %h5{class: 'card-title text-center font-italic'} Gestionar Artistas
  .col-3
    = link_to genres_path, method: 'get', id: 'linksections' do
      .card#card-admin.d-flex
        .card-body.align-items-center.d-flex.justify-content-center
          .row
            .col
              %h5{class: 'card-title text-center font-italic'} Gestionar Generos Musicales
.row.mt-4.bodycontent
  .col-3
    = link_to administration_users_path, method: 'get', id: 'linksections' do
      .card#card-admin.d-flex
        .card-body.align-items-center.d-flex.justify-content-center
          .row
            .col
              %h5{class: 'card-title text-center font-italic'} Gestionar Usuarios

app/views/admins/manageusers.html.haml
.row.mb-3.headercontent
  .col-1
    = link_to administration_path, method: 'get' do
      = image_tag 'izquierda.svg'
.row.headercontent
  .col-3
    = image_tag 'user.svg'
  .col-9
    .row.contenttitle.d-flex.justify-content-center.mb-2
      Gestión de usuarios
    .row.contenttext.text-muted
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
    .row.signindiv.mt-2
      .col.d-flex.justify-content-end
        = link_to  payments_pending_path, method: 'get', class: 'btn', id: 'signinbutton' do
          Verificar Pagos
#lineaseparadora.mt-2
  %hr
.row.mt-4.d-flex.justify-content-center.bodycontent.mb-5
  .col-10
    %table#tablausers
      %thead{id: 'headtabla'}
        %tr
          %th
            .row.d-flex.justify-content-center
              E-MAIL
          %th
            .row.d-flex.justify-content-center
              ESTADO
          %th
            .row.d-flex.justify-content-center
              PAGOS           
      %tbody
        - @users.each do |user|
          %tr
            %td{id: 'campotabla'} 
              .row.d-flex.justify-content-center
                = user.email            
            %td{id: 'campotabla'} 
              - if user.status == 'activo' 
                .row.d-flex.justify-content-around
                  = image_tag 'greencircle.svg'
                  .userstatusactive.text-capitalize= user.status                         
              - else
                .row.d-flex.justify-content-around
                  = image_tag 'yellowcircle.svg'
                  .userstatusinactive.text-capitalize= user.status  
            %td{id: 'campotabla'} 
              .row.d-flex.justify-content-center
                = link_to  user_payments_path(user.id) do
                  = image_tag 'tarjeta2.svg'

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no", :name => "viewport"}/
    %title Monitor Radial
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link{:href => "https://fonts.googleapis.com/css?family=Karla", :rel => "stylesheet"}/
    %link{:href => "https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css", :rel => "stylesheet", :type => "text/css"}/
    %script{:charset => "utf8", :src => "https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js", :type => "text/javascript"}
  %body
    .container
      .row.website
        .col-2.sidebar
          = render 'shared/sidebar', user: current_user
        .col-10.contentadmin.offset-2
          #notice= render 'shared/alertsuccess' if (flash[:notice])
          #error= render 'shared/alerterror' if (flash[:alert]) if (controller_name != 'sessions')
          = yield

app/views/layouts/animation.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no", :name => "viewport"}/
    %title Monitor Radial
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link{:href => "https://fonts.googleapis.com/css?family=Karla", :rel => "stylesheet"}/
    %link{:href => "https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css", :rel => "stylesheet", :type => "text/css"}/
    %script{:charset => "utf8", :src => "https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js", :type => "text/javascript"}
  %body
    .animation
      .animationcontent.d-flex.align-items-center.flex-column
        .row.logoanimation.mb-2
          = image_tag 'monitoranimation.svg', alt: '', height: '', width: '', class: ''
        .row.logoanimation.mb-3
          = image_tag 'radialanimation.svg', alt: '', height: '', width: '', class: ''
        .preloader.mb-3
        %h6 CARGANDO
    .container
      .row.website
        .col-2.sidebar
          = render 'shared/sidebar', user: current_user
        .col-10.content.offset-2
          #notice= render 'shared/alertsuccess' if (flash[:notice])
          #error= render 'shared/alerterror' if (flash[:alert]) if (controller_name != 'sessions')
          = yield

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no", :name => "viewport"}/
    %title Monitor Radial
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link{:href => "https://fonts.googleapis.com/css?family=Karla", :rel => "stylesheet"}/
    %link{:href => "https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css", :rel => "stylesheet", :type => "text/css"}/
    %script{:charset => "utf8", :src => "https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js", :type => "text/javascript"}
  %body
    .container
      .row.website
        .col-2.sidebar
          = render 'shared/sidebar', user: current_user
        .col-10.content.offset-2
          #notice= render 'shared/alertsuccess' if (flash[:notice])
          #error= render 'shared/alerterror' if (flash[:alert]) if (controller_name != 'sessions')
          = yield

app/views/shared/_alert.html.haml
-if devise_error_messages!.present?
  .row.justify-content-center.headercontent
    .col-8
      .alert.alert-warning.alert-dismissible.fade.show
        .text-info= devise_error_messages!
        %button.close{ 'data-dismiss': 'alert' }
          %span x
-else
  .row.justify-content-center.headercontent
    .col-8
      #error_explanation
        .alert.alert-warning.alert-dismissible.fade.show
          %h5.text-center.text-info= "¡ #{flash.alert} !"
          %button.close{ 'data-dismiss': 'alert' }
            %span x

app/views/shared/_alerterror.html.haml
.alert.alert-danger.alert-dismissible.fade.show.headercontent
	= flash[:alert]
	%button.close{ 'data-dismiss': 'alert' }
		%span x
		/ #error= render 'shared/alerterror' if (flash[:alert])

app/views/shared/_alertsuccess.html.haml
.alert.alert-primary.alert-dismissible.fade.show.headercontent
  .text-info= notice
  %button.close{ 'data-dismiss': 'alert' }
    %span x

app/views/shared/_billboard_suscriptors.html.haml
.row.headercontent
  .col-3
    = image_tag 'radio.svg'
  .col-9
    .row.contenttitle.d-flex.justify-content-center.mb-2
      Dashboard de la Cartelera Semanal
    .row.contenttext.text-muted
      Esta clasificación se basa en la difusión recibida por cada título seleccionado en 22 estaciones de radio, distribuidas entre Caracas, el centro, oriente y occidente del país, tomando en cuenta la audiencia que cada una de ellas tiene en los sondeos más recientes. Margen de Error ± 3%.
#lineaseparadora.mt-2
  %hr
.row.mt-4.bodycontent
  .col-3
    = link_to billboard_top_100_path, id: 'linksections' do
      .card#card-background.first-img
        = image_tag ('back-chart-1.png'), class: 'card-img-top top', height: '150px', width: '75px'
        .overlay
          = image_tag ('top100.svg'), class: 'second-img', height: '150px', width: '200px'
        %span{class: 'card-text text-center'}Top 100
  .col-3
    = link_to billboard_top_latino_path, id: 'linksections' do
      .card#card-background.first-img
        = image_tag ('back-chart-2.png'), class: 'card-img-top top', height: '150px', width: '75px'
        .overlay
          = image_tag ('compact-disc.svg'), class: 'second-img', height: '150px', width: '200px'
        %span{class: 'card-text text-center'}Top Latino
  .col-3
    = link_to billboard_top_tradicional_path, id: 'linksections' do
      .card#card-background.first-img
        = image_tag ('back-chart-3.png'), class: 'card-img-top top', height: '150px', width: '75px'
        .overlay
          = image_tag ('music-player.svg'), class: 'second-img', height: '150px', width: '200px'
        %span{class: 'card-text text-center'}Top Tradicional
  .col-3
    = link_to billboard_top_balada_path, id: 'linksections' do
      .card#card-background.first-img
        = image_tag ('back-chart-4.png'), class: 'card-img-top top', height: '150px', width: '75px'
        .overlay
          = image_tag ('karaoke.svg'), class: 'second-img', height: '150px', width: '200px'
        %span{class: 'card-text text-center'}Top Balada
.row.mt-4.bodycontent.mb-5
  .col-3
    = link_to billboard_top_salsa_path, id: 'linksections' do
      .card#card-background.first-img
        = image_tag ('back-chart-5.png'), class: 'card-img-top top', height: '150px', width: '75px'
        .overlay
          = image_tag ('dancing.svg'), class: 'second-img', height: '150px', width: '200px'
        %span{class: 'card-text text-center'}Top Salsa
  .col-3
    = link_to billboard_top_pop_path, id: 'linksections' do
      .card#card-background.first-img
        = image_tag ('back-chart-6.png'), class: 'card-img-top top', height: '150px', width: '75px'
        .overlay
          = image_tag ('rock-and-roll.svg'), class: 'second-img', height: '150px', width: '200px'
        %span{class: 'card-text text-center'}Top Pop
  .col-3
    = link_to billboard_top_rock_path, id: 'linksections' do
      .card#card-background.first-img
        = image_tag ('back-chart-7.png'), class: 'card-img-top top', height: '150px', width: '75px'
        .overlay
          = image_tag ('shirt.svg'), class: 'second-img', height: '150px', width: '200px'
        %span{class: 'card-text text-center'}Top Rock
  .col-3
    = link_to billboard_top_emisoras_path, id: 'linksections' do
      .card#card-background.first-img
        = image_tag ('back-chart-8.png'), class: 'card-img-top top', height: '150px', width: '75px'
        .overlay
          = image_tag ('radio-antenna.svg'), class: 'second-img', height: '150px', width: '200px'
        %span{class: 'card-text text-center'}Top Emisoras

app/views/shared/_broadcasterform.html.haml
.row.mb-3.headercontent
  .col-1
    = link_to broadcasters_manage_path, method: 'get' do
      = image_tag 'izquierda.svg'
.row.headercontent
  .container.mt-5
    %h2{class: 'text-center'} Agregar Emisora Radial
    = form_with(model: @broadcaster, local: true, id: "radioform" ) do |form|
      - if @broadcaster.errors.any?
        #error_explanation.alert.alert-danger.alert-dismissible.fade.show.font-happy-alert
          %h4= "#{pluralize(@broadcaster.errors.count, "error")} al intentar guardar la emisora:"
          %ul
            - @broadcaster.errors.full_messages.each do |message|
              %li= message
          %button.close{ 'data-dismiss': 'alert' }
            %span x
      .row.form-group.justify-content-center
        .col-5
          = form.label :name, 'Nombre'
          = form.text_field :name, autofocus: true, autocomplete: "nombre", class: 'form-control', required: 'true'
        .col-5
          = form.label :ref, 'Referencia'
          = form.text_field :ref, autofocus: true, autocomplete: "referencia", class: 'form-control', required: 'true'
      .row.form-group.justify-content-center
        .col-5
          = form.label :email, 'E-mail'
          = form.email_field :email, autofocus: true, autocomplete: "email", class: 'form-control', required: 'true'
        .col-5
          = form.label :phone, 'Teléfono'
          = form.text_field :phone, autofocus: true, autocomplete: "teléfono", class: 'form-control', required: 'true'
      .row.form-group.justify-content-center
        .col-5
          = form.label :location, 'Ubicación'
          = form.text_field :location, autofocus: true, autocomplete: "ubicación", class: 'form-control', required: 'true'
        .col-5
          = form.label :contact_name, 'Responsable'
          = form.text_field :contact_name, autofocus: true, autocomplete: "responsable", class: 'form-control', required: 'true'
      .row.form-group.justify-content-center.mt-5
        .col-12
          .actions.text-center
            = form.submit "Guardar", class: 'btn', id: 'form-user-button'

app/views/shared/_datalist_form.html.haml
.row
  .col-12
    .row.justify-content-center.mb-3.mt-3
      .col-10
        .row
          Estimado administrador, para añadir una lista de canciones sonadas en el dia en una de las emisoras analizadas, debes adjuntar un archivo en formato .txt con el siguiente formato:
    .row.justify-content-center
      = image_tag ('añadirpago.svg'), data: { target: '#modalpagos', toggle: 'modal', id: 'imagepointer' }
    .row.justify-content-center.mt-3
      %button.btn#form-user-button{ data: { target: '#modalpagos', toggle: 'modal' } }
        Quiero enviar una lista!
    #modalpagos.modal.fade.mt-5
      .modal-dialog
        .modal-content#contenidodelmodal
          .modal-header.text-center.shadow.p-3.rounded.mb-2
            %h4.modal-title.white-text.w-100.font-weight-bold.py-2 Nueva Lista
            %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
              %span.white-text{"aria-hidden" => "true"} ×
          .modal-body
            = form_with(model: @datalist, local: true, id: "listform") do |form|
              .field
                .row.form-group
                  .col-sm-12.col-form-label
                    .font-roboto-form= form.label :list, 'Lista:'
                    = form.file_field :list, class: 'dropify'
                = form.hidden_field :list_date, value: Time.now.strftime('%Y-%m-%d')
              .actions
                .row.mt-4
                  .col.text-center
                    = form.submit("CARGAR",:class => "btn btn-lg", :id => "form-user-button")

app/views/shared/_genre_form.html.haml
.container
  .row.mb-5.headercontent
    .col-1
      = link_to genres_path, method: 'get' do
        = image_tag 'izquierda.svg'
  .row.bodycontent
    .col.mt-5
      %h1.text-center Agregar Género Musical
      %hr
      #notice= render 'shared/alertsuccess' if (flash[:notice])
      #error= render 'shared/alerterror' if (flash[:alert])
      = form_with(model: @genre, local: true, id: "genreform" ) do |form|
        - if @genre.errors.any?
          #error_explanation.alert.alert-danger.alert-dismissible.fade.show.font-happy-alert
            %h4= "#{pluralize(@genre.errors.count, "error")} al intentar guardar el género musical:"
            %ul
              - @genre.errors.full_messages.each do |message|
                %li= message
            %button.close{ 'data-dismiss': 'alert' }
              %span x
        .form-group
          .row.justify-content-center
            .col-6
              = form.label :name, 'Nombre del género:'
              = form.text_field :name, class:'form-control', required: 'true'
        .actions.text-center
          = form.submit "Guardar", class: 'btn', id: 'form-user-button'

app/views/shared/_new_payment_user_active.html.haml
.row.justify-content-center.mt-5.bodycontent
  .col-6
    = image_tag 'vip.svg', height: '350px', width: '500px'
.row.justify-content-center.mt-3
  .col-4
    %h5.font-italic Usted posee una suscripción activa

app/views/shared/_sidebar.html.haml
.sidebarcontent.col-2
  .row.logodiv.mt-5
    .col
      .row
        .col.d-flex.justify-content-center.monitor
          = image_tag 'Monitor.svg'
      .row
        .col.d-flex.justify-content-center.radial.mt-2
          = image_tag 'Radial.svg'
  .row.sidebarlistdiv
    %ul.__sidebarlist.mt-5.mb-5
      - if current_user.present?
        %li.mb-3
          .row#useremail.d-flex.justify-content-center
            .font-italic Bienvenido
          .row#useremail.d-flex.justify-content-center
            .font-italic.text-capitalize= current_user.email.split('@')[0]
      - if controller_name != 'home'
        %li.__sidebarlink
          = link_to root_path, method: 'get', id: '__linksections' do
            = image_tag 'homeblanco.svg'
            Inicio
      - else
        %li.__sidebarlinkselected
          #__linksections
            = image_tag 'homeblanco.svg'
            Inicio
      %li.__sidebarlink
        = link_to billboard_path, method: 'get', id: '__linksections' do
          = image_tag 'carteleras.svg'
          Carteleras
      - if current_user.present? && current_user.role == 'admin'
        - if controller_name == 'admins' || (controller_name == 'broadcasters' && action_name == 'new') || (controller_name == 'broadcasters' && action_name == 'edit') || (controller_name == 'broadcasters' && action_name == 'manage')
          %li.__sidebarlinkselected
            #__linksections
              = image_tag 'adminsidebar.svg'
              Administrar
        - else
          %li.__sidebarlink
            = link_to administration_path, method: 'get', id: '__linksections' do
              = image_tag 'adminsidebar.svg'
              Administrar
      -if current_user.present? && current_user.role == 'regular'
        - if controller_name != 'payments'
          %li.__sidebarlink
            = link_to new_user_payment_path(user_id: current_user.id), method: 'get', id: '__linksections' do
              = image_tag 'usersidebar.svg'
              Mi cuenta
        - else
          %li.__sidebarlinkselected
            #__linksections
              = image_tag 'usersidebar.svg'
              Mi cuenta
      -if current_user.blank?
        -if controller_name != 'subscription'
          %li.__sidebarlink
            = link_to subscriptions_path, method: 'get', id: '__linksections' do
              = image_tag 'subscripcion.svg'
              Suscripción
        - else
          %li.__sidebarlinkselected
            #__linksections
              = image_tag 'subscripcion.svg'
              Suscripción
      - if controller_name == 'broadcasters' && action_name == 'index'
        %li.__sidebarlinkselected
          #__linksections
            = image_tag 'emisoras.svg'
            Emisoras
      - else
        %li.__sidebarlink
          = link_to broadcasters_path, method: 'get', id: '__linksections' do
            = image_tag 'emisoras.svg'
            Emisoras
      %li.__sidebarlink
        = link_to contact_path, method: 'get', id: '__linksections' do
          = image_tag 'phone.svg'
          Contacto
  -if (controller_name != 'passwords') && (controller_name != 'sessions')
    - if current_user.blank?
      .row.signindiv.mt-3
        .col.d-flex.justify-content-center
          = link_to user_session_path, method: 'get', class: 'btn', id: 'signinbutton' do
            Iniciar sesión
    - else
      .row.signindiv.mt-3
        .col.d-flex.justify-content-center
          = link_to destroy_user_session_path, method: 'delete', class: 'btn', id: 'signinbutton' do
            Cerrar sesión

app/views/shared/_status_user.html.haml
=form_with(model: @user, local: true) do |form|
  = form.check_box :status
  .actions.text-center
    = form.submit "Procesar", class: 'btn', id: 'form-user-button'

app/views/shared/_subscription.html.haml
.col-12
  .row.headercontent
    .col-3
      = image_tag 'podcast.svg'
    .col-9
      .row.suscriptiontitle.mb-2
        Suscripción en Monitor Radial
      .row.contenttext.text-muted
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
  #lineaseparadora.mt-2
    %hr  
  .row.bodycontent
    .col-12
      .card#inforectangle.mb-4.mt-5.contenttext
        %ul
          %li.mb-4
            Top 100: Muestra las 100 canciones más sonadas en las emisoras monitoreadas durante la última semana, señala la posición que tiene en Esta Semana, la posición de la Semana Anterior, el número de Semanas en Cartelera, título, intérprete y sello disquero. Se actualiza cada jueves después de las 12:00 M.
          %li
            Latin40: Una observación particular sobre la misma muestra anterior aplicada sólo al producto en lengua hispana producido fuera del territorio venezolano. Se actualiza cada jueves después de las 12:00M.
  .row
    .col.d-flex.justify-content-center
      -if current_user.present? && current_user.role == 'regular'
        = link_to "Enviar Pago", new_user_payment_path(user_id: current_user.id), class: 'btn', id: 'form-user-button'
      -else
        = link_to "Registrarse", new_user_registration_path, class: 'btn', id: 'form-user-button'