config/routes.rb
Rails.application.routes.draw do
  resources :songs do
    collection { post :import}
  end
  get 'subscriptions', to: 'subscription#index'
  devise_for :users, :paths => 'users'
  resources :users do
    resources :payments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :broadcasters, except: [:show]
  resources :genres
  resources :datalists, only: [:new, :create]
  get 'payments/pending', to: 'payments#pendingpayments'
  # patch 'payments/pending', to: 'payments#update'
  get 'broadcasters/manage', to: 'broadcasters#manage'
  get 'administration/users', to: 'admins#manageusers'
  get 'administration', to: 'admins#index'
  get 'billboard', to: 'billboards#index'
  get 'billboard/top_100', to: 'billboards#top_100'
  get 'billboard/top_latino', to: 'billboards#top_latino'
  get 'billboard/top_tradicional', to: 'billboards#top_tradicional'
  get 'billboard/top_balada', to: 'billboards#top_balada'
  get 'billboard/top_salsa', to: 'billboards#top_salsa'
  get 'billboard/top_pop', to: 'billboards#top_pop'
  get 'billboard/top_rock', to: 'billboards#top_rock'
  get 'billboard/top_emisoras', to: 'billboards#top_emisoras'
  get 'contact', to: 'contact#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/broadcaster.rb
class Broadcaster < ApplicationRecord
  validates :name, :email, :phone, :ref, :location, :contact_name, presence: true
  validates :name, uniqueness: true
end

app/models/datalist.rb
class Datalist < ApplicationRecord
  # validates :list_date, :list, presence: true
  has_one_attached :list
  validate :correct_file_type

  private

  def correct_file_type
    if list.attached? && !list.content_type.in?(%w(text/plain))
      errors.add(:list, 'Seleccionar solo archivos con extensión .txt /')
    end
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
  enum paid_out: [:pendiente, :procesado]
  validates :invoice, :paid_out, presence: true
  validate :correct_file_type
  has_one_attached :invoice

  # after_update :set_user_active
  accepts_nested_attributes_for :user, update_only: true

  private

    def correct_file_type
      if invoice.attached? && !invoice.content_type.in?(%w(image/jpg image/jpeg image/png application/pdf))
        errors.add(:invoice, 'Seleccionar solo archivos con extensión .jpg / .jpeg / .png / .pdf')
      end
    end

    # def set_user_active
    #   @user = User.find(params[:id])
    #   @user.status = 'activo'
    #   @user.save
    # end
end

app/models/song.rb
class Song < ApplicationRecord
  require 'csv'
  # validate :correct_file_type

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Song.create! row.to_hash
    end
  end

  private

  # def correct_file_type
  #   if file.attached? && !file.content_type.in?(%w(text/csv))
  #     errors.add(:file, 'Seleccionar solo archivos con extensión .csv /')
  #   end
  # end

end

app/models/user.rb
class User < ApplicationRecord
  enum role: [:regular, :admin]
  enum status: [:inactivo, :activo]
  has_many :payments

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  after_initialize :set_default_role, :set_default_status, :if => :new_record?

  # accepts_nested_attributes_for :payments, reject_if: :all_blank

  def set_default_role
    self.role ||= :regular
  end

  def set_default_status
    self.status ||= :inactivo
  end

end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin
  layout :resolve_layout
  def index
  end

  def manageusers
    @users = User.where(role: 'regular')

  end

  private

  def authenticate_admin
    if current_user.role != 'admin'
      redirect_back fallback_location: root_path, alert: "No posee los permisos necesarios"
    end
  end

  def resolve_layout
    case action_name
    when "manageusers"
      "admin"
    end
  end

end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre, only: [:show, :edit, :update, :destroy]
  layout :resolve_layout
  def index
    @genres = Genre.all
  end

  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to genres_path, notice: '¡ Género Musical Agregado Correctamente !'
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @genre.update(genre_params)
      redirect_to genres_path, notice: '¡ Género Musical Actualizado Correctamente !'
    else
      redirect_to genres_path, alert: '¡ No se pudo Actualizar el registro seleccionado !'
    end
  end

  def destroy
    if @genre.destroy
      redirect_to genres_path, notice: '¡ Género Musical Eliminado Correctamente !'
    else
      redirect_to genres_path, alert: '¡ No se pudo Elimina el registro seleccionado !'
    end
  end

  private

  def set_genre
    @genre = Genre.find(params[:id])
  end

  def genre_params
    params.require(:genre).permit(:name)
  end

  def resolve_layout
    case action_name
    when "index", "new"
      "admin"
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'animation'
  def index
    
  end
  
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin, except: [:new, :create]
  before_action :set_payment, only: [:edit, :update]
  layout :resolve_layout
def index
  @user = User.find(params[:user_id])
  @payments = Payment.all.where(user_id: @user).order(created_at: :desc)
end

def pendingpayments
  @payments = Payment.all.where(paid_out: 0)
end

def new
  @user = User.find(params[:user_id])
  @payment = Payment.new()
end

def create
  @user = User.find(params[:user_id])
  @payment = @user.payments.build(payment_params)
  respond_to do |format|
    if @payment.save
      UserMailer.send_pay(@user).deliver
      UserMailer.confirmation(@user).deliver
      format.html { redirect_to new_user_payment_path, notice: '¡ Recibo enviado correctamente, una vez confirmado el pago, recibirá una notificación por correo electrónico!' }
    else
      format.html { redirect_to new_user_payment_path, alert: '¡ Pago no enviado, el formato del archivo es incorrecto!'  }
    end
  end
end

def edit
  @user = User.find(params[:user_id])
end

def update
  @user = User.find(params[:user_id])
  if @payment.update(payment_params)
    UserMailer.notify(@user).deliver
    redirect_to user_payments_path(@user,@payments), notice: 'Registros procesados correctamente'
  else
    redirect_to payments_pending_path, alert: 'No se pudo procesar el pago seleccionado'
  end

  # render json: @payment
end

private

def authenticate_admin
  if current_user.role != 'admin'
    redirect_back fallback_location: root_path, alert: "No posee los permisos necesarios"
  end
end

def set_payment
  @payment = Payment.find(params[:id])
end

def payment_params
  params.require(:payment).permit(:paid_out, :invoice, user_attributes: [:status])
end

def user_params
  params.require(:user).permit(status:[])
end

def resolve_layout
  case action_name
  when "index", "pendingpayments", "edit"
    "admin"
  end
end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin
  layout :resolve_layout
  def new
  end

  def create
    Song.import(params[:file])
    redirect_to new_song_path, notice: "Lista de canciones agregadas correctamente!"
  end

  private
  def authenticate_admin
    if current_user.role != 'admin'
      redirect_back fallback_location: root_path, alert: "No posee los permisos necesarios"
    end
  end


  def resolve_layout
    case action_name
    when "new"
      "admin"
    end
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/billboards_helper.rb
module BillboardsHelper
end

app/helpers/broadcasters_helper.rb
module BroadcastersHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/datalists_helper.rb
module DatalistsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/subscription_helper.rb
module SubscriptionHelper
end

app/views/payments/edit.html.haml
.row.mb-3.headercontent
  .col-1
    = link_to user_payments_path(@payment.user_id), method: 'get' do
      = image_tag 'izquierda.svg'
.row.headercontent
  .col-3
    = image_tag 'user.svg'
  .col-9
    .row.contenttitle.d-flex.justify-content-center.mb-2
      Procesar pago seleccionado
    .row.contenttext.text-muted
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
= form_with(model: [@user, @payment], local: true) do |form|
  .row.form-group.justify-content-center.mt-5
    .col-6.form-label
      = form.label :paid_out, 'Estatus del Pago'
      = form.select :paid_out, ['procesado'], {include_blank: 'Seleccione'}, {class:'form-control custom-select text-capitalize'} #Payment.paid_outs.keys
      = form.fields_for :user, @user do |userform|
        = userform.hidden_field :status, value: 'activo'
  .row.form-group.justify-content-center
    .col-6.form-label
      .actions
        = form.submit 'Procesar Pago', class: 'btn', id: 'form-user-button'

app/views/payments/index.html.haml
.row.mb-3.headercontent
  .col-1
    = link_to administration_users_path, method: 'get' do
      = image_tag 'izquierda.svg'
.row.headercontent
  .col-3
    = image_tag 'user.svg'
  .col-9
    .row.contenttitle.d-flex.justify-content-center.mb-2
      Verificación de Pagos por Usuario
    .row.contenttext.text-muted
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
#lineaseparadora.mt-2
%hr
-if @payments.present?
  .row.mt-3.justify-content-center.bodycontent.mb-5
    .col-7
      %table{class: 'table table-hover table-bordered', id: 'genreborder'}
        %thead.text-center
          %tr
            %th{colspan: '4'} Pagos realizados por el usuario
        %tbody.text-center
          - @payments.each do |payment|
            %tr
              %td= payment.user.email
              %td{class:'text-capitalize'}= payment.paid_out
              %td= link_to 'Ver Pago',url_for(payment.invoice), target: "_blank", id: 'see-payment'
              -# -if payment.paid_out == 'pendiente'
              -#   %td= link_to 'Procesar', edit_user_payment_path(payment.user_id, payment.id), class:'btn', id: 'form-user-button'
- else
  .row.mt-5.justify-content-center.bodycontent
    .col-6
      .row
        = image_tag 'credit_card.svg', height: '350px', width: '500px', class: 'processing-paid'
  .row.mt-3.justify-content-center.bodycontent.mb-5
    .col-5
      %h3{class: 'font-italic text-center'} No Existen Pagos Realizados por el Usuario

app/views/payments/new.html.haml
.row.headercontent
  .col-3
    = image_tag 'radio.svg'
  .col-9
    .row.contenttitle.d-flex.justify-content-center.mb-2
      Mi cuenta
    .row.contenttext.text-muted
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
#lineaseparadora.mt-2
  %hr
-if (@user.status == 'activo')
  = render 'shared/new_payment_user_active'
- else
  = render 'shared/new_payment_user_inactive', locals: {user: @user, payment: @payment}

app/views/payments/pendingpayments.html.haml
.row.mb-3.headercontent
  .col-1
    = link_to administration_users_path, method: 'get' do
      = image_tag 'izquierda.svg'
.row.headercontent
  .col-3
    = image_tag 'user.svg'
  .col-9
    .row.contenttitle.d-flex.justify-content-center.mb-2
      Verificación de Pagos Pendientes
    .row.contenttext.text-muted
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
#lineaseparadora.mt-2
%hr

-if @payments.present?
  .row.mt-3.justify-content-center.bodycontent.mb-5
    .col-7
      %table{class: 'table table-hover table-bordered', id: 'genreborder'}
        %thead.text-center
          %tr
            %th{colspan: '3'} Pagos pendientes por Procesar
            %th Acción
        %tbody.text-center
          - @payments.each do |payment|
            %tr
              %td= payment.user.email
              %td{class:'text-capitalize'}= payment.paid_out
              %td= link_to 'Ver Pago', url_for(payment.invoice), target: "_blank", id: 'see-payment'
              %td= link_to 'Procesar', edit_user_payment_path(user_id: payment.user.id, id: payment.id), class:'btn', id: 'form-user-button'
-else
  .row.mt-5.justify-content-center.bodycontent
    .col-6
      .row
        = image_tag 'undraw_no_data_qbuo.svg', height: '350px', width: '500px', class: 'processing-paid'
  .row.mt-3.justify-content-center.bodycontent.mb-5
    .col-6
      %h3{class: 'font-italic'} No Existen Registros por procesar