config/routes.rb
Rails.application.routes.draw do
  resources :songs do
    collection { post :import}
  end
  get 'subscriptions', to: 'subscription#index'
  devise_for :users, :paths => 'users'
  resources :users do
    resources :payments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :broadcasters, except: [:show]
  resources :genres
  resources :datalists, only: [:new, :create]
  get 'payments/pending', to: 'payments#pendingpayments'
  # patch 'payments/pending', to: 'payments#update'
  get 'broadcasters/manage', to: 'broadcasters#manage'
  get 'administration/users', to: 'admins#manageusers'
  get 'administration', to: 'admins#index'
  get 'billboard', to: 'billboards#index'
  get 'billboard/top_100', to: 'billboards#top_100'
  get 'billboard/top_latino', to: 'billboards#top_latino'
  get 'billboard/top_tradicional', to: 'billboards#top_tradicional'
  get 'billboard/top_balada', to: 'billboards#top_balada'
  get 'billboard/top_salsa', to: 'billboards#top_salsa'
  get 'billboard/top_pop', to: 'billboards#top_pop'
  get 'billboard/top_rock', to: 'billboards#top_rock'
  get 'billboard/top_emisoras', to: 'billboards#top_emisoras'
  get 'contact', to: 'contact#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/broadcaster.rb
class Broadcaster < ApplicationRecord
  validates :name, :email, :phone, :ref, :location, :contact_name, presence: true
  validates :name, uniqueness: true
end

app/models/datalist.rb
class Datalist < ApplicationRecord
  # validates :list_date, :list, presence: true
  has_one_attached :list
  validate :correct_file_type

  private

  def correct_file_type
    if list.attached? && !list.content_type.in?(%w(text/plain))
      errors.add(:list, 'Seleccionar solo archivos con extensión .txt /')
    end
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
  enum paid_out: [:pendiente, :procesado]
  validates :invoice, :paid_out, presence: true
  validate :correct_file_type
  has_one_attached :invoice

  # after_update :set_user_active
  accepts_nested_attributes_for :user, update_only: true

  private

    def correct_file_type
      if invoice.attached? && !invoice.content_type.in?(%w(image/jpg image/jpeg image/png application/pdf))
        errors.add(:invoice, 'Seleccionar solo archivos con extensión .jpg / .jpeg / .png / .pdf')
      end
    end

    # def set_user_active
    #   @user = User.find(params[:id])
    #   @user.status = 'activo'
    #   @user.save
    # end
end

app/models/song.rb
class Song < ApplicationRecord
  require 'csv'
  # validate :correct_file_type

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Song.create! row.to_hash
    end
  end

  private

  # def correct_file_type
  #   if file.attached? && !file.content_type.in?(%w(text/csv))
  #     errors.add(:file, 'Seleccionar solo archivos con extensión .csv /')
  #   end
  # end

end

app/models/user.rb
class User < ApplicationRecord
  enum role: [:regular, :admin]
  enum status: [:inactivo, :activo]
  has_many :payments

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  after_initialize :set_default_role, :set_default_status, :if => :new_record?

  # accepts_nested_attributes_for :payments, reject_if: :all_blank

  def set_default_role
    self.role ||= :regular
  end

  def set_default_status
    self.status ||= :inactivo
  end

end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin
  layout :resolve_layout
  def index
  end

  def manageusers
    @users = User.where(role: 'regular')

  end

  private

  def authenticate_admin
    if current_user.role != 'admin'
      redirect_back fallback_location: root_path, alert: "No posee los permisos necesarios"
    end
  end

  def resolve_layout
    case action_name
    when "manageusers"
      "admin"
    end
  end

end

app/controllers/broadcasters_controller.rb
class BroadcastersController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :authenticate_admin, except: [:index]
  before_action :set_broadcaster, only: [:edit, :update, :destroy]
  layout :resolve_layout

  def manage
    @broadcasters = Broadcaster.all
  end

  def index
    @broadcasters = Broadcaster.all
  end

  def new
    @broadcaster = Broadcaster.new()
  end

  def create
    @broadcaster = Broadcaster.new(broadcaster_params)
    if @broadcaster.save
        redirect_to broadcasters_manage_path(), notice: '¡ Emisora Agregada Correctamente !'
    else
      render :new
    end  
  end

  def edit
    
  end

  def update
    if @broadcaster.update(broadcaster_params)
      redirect_to broadcasters_manage_path, notice: 'Emisora Modificada Correctamente.'
    else
      render :edit
    end
  end

  def destroy
    respond_to do |format|
      if @broadcaster.destroy
        format.html { redirect_to broadcasters_manage_path, notice: '¡ Emisora Eliminada Correctamente !'}
      else
        format.html { redirect_to broadcasters_manage_path, notice: '¡ No se pudo Eliminar la Emisora seleccionada !'}
      end
    end

  end

  private
  def authenticate_admin
    if current_user.role != 'admin'
      redirect_back fallback_location: root_path, alert: "No posee los permisos necesarios"
    end  
  end

  def broadcaster_params
    params.require(:broadcaster).permit(:name, :email, :phone, :ref, :location, :contact_name, :id)
  end

  def set_broadcaster
    @broadcaster = Broadcaster.find(params[:id])
  end

  def resolve_layout
    case action_name
    when "manage", "new"
      "admin"
    end
  end

end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre, only: [:show, :edit, :update, :destroy]
  layout :resolve_layout
  def index
    @genres = Genre.all
  end

  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to genres_path, notice: '¡ Género Musical Agregado Correctamente !'
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @genre.update(genre_params)
      redirect_to genres_path, notice: '¡ Género Musical Actualizado Correctamente !'
    else
      redirect_to genres_path, alert: '¡ No se pudo Actualizar el registro seleccionado !'
    end
  end

  def destroy
    if @genre.destroy
      redirect_to genres_path, notice: '¡ Género Musical Eliminado Correctamente !'
    else
      redirect_to genres_path, alert: '¡ No se pudo Elimina el registro seleccionado !'
    end
  end

  private

  def set_genre
    @genre = Genre.find(params[:id])
  end

  def genre_params
    params.require(:genre).permit(:name)
  end

  def resolve_layout
    case action_name
    when "index", "new"
      "admin"
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'animation'
  def index
    
  end
  
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin
  layout :resolve_layout
  def new
  end

  def create
    Song.import(params[:file])
    redirect_to new_song_path, notice: "Lista de canciones agregadas correctamente!"
  end

  private
  def authenticate_admin
    if current_user.role != 'admin'
      redirect_back fallback_location: root_path, alert: "No posee los permisos necesarios"
    end
  end


  def resolve_layout
    case action_name
    when "new"
      "admin"
    end
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/billboards_helper.rb
module BillboardsHelper
end

app/helpers/broadcasters_helper.rb
module BroadcastersHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/datalists_helper.rb
module DatalistsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/subscription_helper.rb
module SubscriptionHelper
end

app/views/broadcasters/edit.html.haml
= render 'shared/broadcasterform', locals: {broadcaster: @broadcaster}

app/views/broadcasters/index.html.haml
.row.headercontent
  .col-3
    = image_tag 'music.svg'
  .col-9
    .row.contenttitle.d-flex.justify-content-center.mb-2
      Emisoras de radio analizadas
    .row.contenttext.text-muted
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
#lineaseparadora.mt-2
  %hr
.row.mt-4.bodycontent.mb-5
  .col-12
    .card#statsrectangleadmin
      .cardheader#headerbroadcastersadmin
        .row.mb-4
          .col-3.thisweekheader.d-flex.align-items-center.justify-content-center
            ESTACIÓN
          .col-1.lastweekheader.d-flex.align-items-center.justify-content-center
            REF.
          .col-2.dashboardweeksheader.d-flex.align-items-center.justify-content-center
            UBICACIÓN
          .col-2.positionchangeheader.d-flex.align-items-center.justify-content-center
            E-MAIL
          .col-2.positionchangeheader.d-flex.align-items-center.justify-content-center
            TELÉFONO
          .col-2.positionchangeheader.d-flex.align-items-center.justify-content-center
            RESPONSABLE
      - @broadcasters.each do |broadcaster|
        .card-item#itembroadcastersadmin
          .row
            .col-3.thisweek.d-flex.align-items-center.justify-content-center
              = broadcaster.name
            .col-1.lastweek.d-flex.align-items-center.justify-content-center
              = broadcaster.ref
            .col-2.dashboardweeks.d-flex.align-items-center.justify-content-center
              = broadcaster.location
            .col-2.positionchange.d-flex.align-items-center.justify-content-center
              = broadcaster.email
            .col-2.positionchange.d-flex.align-items-center.justify-content-center
              = broadcaster.phone
            .col-2.positionchange.d-flex.align-items-center.justify-content-center
              = broadcaster.contact_name

app/views/broadcasters/manage.html.haml
.row.mb-3.headercontent
  .col-1
    = link_to administration_path, method: 'get' do
      = image_tag 'izquierda.svg'
.row.headercontent
  .col-3
    = image_tag 'radio.svg'
  .col-9
    .row.contenttitle.d-flex.justify-content-center.mb-2
      Gestión de Emisoras Radiales
    .row.contenttext.text-muted
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
    - if @broadcasters.present?
      .row.signindiv.mt-3
        .col.d-flex.justify-content-end
          = link_to new_broadcaster_path, method: 'get', class: 'btn', id: 'signinbutton' do
            Agregar Emisora
#lineaseparadora.mt-2
  %hr
- if @broadcasters.present?
  .row.mt-4.bodycontent.mb-5
    .col-12
      .card#statsrectangleadmin
        .cardheader#headerbroadcastersadmin
          .row.mb-4
            .col-2.thisweekheader.d-flex.align-items-center.justify-content-center
              ESTACIÓN
            .col-1.lastweekheader.d-flex.align-items-center.justify-content-center
              REF.
            .col-2.dashboardweeksheader.d-flex.align-items-center.justify-content-center
              UBICACIÓN
            .col-2.positionchangeheader.d-flex.align-items-center.justify-content-center
              E-MAIL
            .col-2.positionchangeheader.d-flex.align-items-center.justify-content-center
              TELÉFONO
            .col-2.positionchangeheader.d-flex.align-items-center.justify-content-center
              RESPONSABLE
              .col-1.positionchange.d-flex.align-items-center.justify-content-center
        - @broadcasters.each do |broadcaster|
          .card-item#itembroadcastersadmin
            .row
              .col-2.thisweek.d-flex.align-items-center.justify-content-center
                = broadcaster.name
              .col-1.lastweek.d-flex.align-items-center.justify-content-center
                = broadcaster.ref
              .col-2.dashboardweeks.d-flex.align-items-center.justify-content-center
                = broadcaster.location
              .col-2.positionchange.d-flex.align-items-center.justify-content-center
                = broadcaster.email
              .col-2.positionchange.d-flex.align-items-center.justify-content-center
                = broadcaster.phone
              .col-2.positionchange.d-flex.align-items-center.justify-content-center
                = broadcaster.contact_name
              .col-1.positionchange.d-flex.align-items-center.justify-content-center
                .dropdown.dropleft
                  %button#dropdownMenuButton.btn{type: 'button', 'data-toggle':"dropdown", 'aria-haspopup': "true", 'aria-expanded': "false"}
                    = image_tag 'menu.svg'
                  .dropdown-menu#dropdownmenu{"aria-labelledby" => "dropdownMenuButton"}
                    .dropdown-item#dropdownmenuitem
                      =link_to edit_broadcaster_path(id: broadcaster.id), class: '', id: 'optionbutton' do
                        .row
                          .col-3
                            = image_tag 'pencil.svg'
                          .col-9
                            Editar
                    .dropdown-item#dropdownmenuitem
                      =link_to broadcaster_path(id: broadcaster.id), method: :delete, data: { confirm: '¿Esta seguro de eliminar esta emisora?'}, class: '', id: 'optionbutton' do
                        .row
                          .col-3
                            = image_tag 'bin.svg'
                          .col-9
                            Eliminar
- else
  .row.bodycontent
    .col-12
      .row.justify-content-center.mt-5
        = link_to new_broadcaster_path, method: 'get' do
          = image_tag 'añadirpago.svg'
      .row.justify-content-center
        = link_to new_broadcaster_path, method: 'get', id: 'forgot-password' do
          Presiona para agregar una nueva emisora

app/views/broadcasters/new.html.haml
= render 'shared/broadcasterform', locals: {broadcaster: @broadcaster}